apiVersion: v1
kind: Service
metadata:
  labels:
    app.overleaf.service: mongo-{{ include "overleaf.fullname" . }}
  name: mongo-{{ include "overleaf.fullname" . }}
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app.overleaf.service: mongo-{{ include "overleaf.fullname" . }}
status:
  loadBalancer: {}
