apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
  name: mongo-{{ include "overleaf.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "overleaf.selectorLabels" . | nindent 6 }}
      app.overleaf.service: mongo-{{ include "overleaf.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.mongo.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      creationTimestamp: null
      labels:
        {{- include "overleaf.selectorLabels" . | nindent 8 }}
	{{- include "overleaf.network" . | nindent 8 }}
        app.overleaf.service: mongo-{{ include "overleaf.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeName: {{ .Values.mongo.nodeName }}
      containers:
      - image: {{ .Values.mongo.image.name }}:{{ .Values.mongo.image.tag }}
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        #livenessProbe:
        #  exec:
        #    command:
        #    - echo 'db.stats().ok' | mongo localhost:27017/test --quiet
        #  failureThreshold: 5
        #  periodSeconds: 10
        #  timeoutSeconds: 10
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        {{ if .Values.mongo.volumes.name }}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-volume
        {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      {{ if .Values.mongo.volumes.name }}
      volumes:
      - name: mongo-data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.mongo.volumes.name }}
      {{ end }}

status: {}
