apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: overleaf-{{ include "overleaf.fullname" . }}
spec:
  ingress:
  - from:
    - podSelector:
         matchLabels:
           {{- include "overleaf.network" . | nindent 12 }}
  podSelector:
     matchLabels:
       {{- include "overleaf.network" . | nindent 8 }}
