apiVersion: v1
kind: Service
metadata:
  labels:
    app.overleaf.service: redis-{{ include "overleaf.fullname" . }}
  name: redis-{{ include "overleaf.fullname" . }}
  #name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.overleaf.service: redis-{{ include "overleaf.fullname" . }}
status:
  loadBalancer: {}
