apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.overleaf.service: sharelatex-{{ include "overleaf.fullname" . }}
  name: sharelatex
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.overleaf.service: sharelatex-{{ include "overleaf.fullname" . }}
  type: NodePort
status:
  loadBalancer: {}
