apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
  name: sharelatex-{{ include "overleaf.fullname" . }}
spec:
  replicas: {{ .Values.sharelatex.replicaCount }}
  selector:
    matchLabels:
      {{- include "overleaf.selectorLabels" . | nindent 6 }}
      app.overleaf.service: sharelatex-{{ include "overleaf.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.sharelatex.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      creationTimestamp: null
      labels:
        {{- include "overleaf.selectorLabels" . | nindent 8 }}
        {{- include "overleaf.network" . | nindent 8 }}
        app.overleaf.service: sharelatex-{{ include "overleaf.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeName: {{ .Values.sharelatex.nodeName }}
      containers:
      - env:
        - name: EMAIL_CONFIRMATION_DISABLED
          value: "true"
        - name: ENABLED_LINKED_FILE_TYPES
          value: url,project_file
        - name: ENABLE_CONVERSIONS
          value: "true"
        - name: REDIS_HOST
          value: redis-{{ include "overleaf.fullname" . }}
        - name: SHARELATEX_APP_NAME
          value: Overleaf Community Edition
        - name: SHARELATEX_MONGO_URL
          value: mongodb://mongo-{{ include "overleaf.fullname" . }}/sharelatex
        - name: SHARELATEX_REDIS_HOST
          value: redis-{{ include "overleaf.fullname" . }}
        - name: TEXMFVAR
          value: /var/lib/sharelatex/tmp/texmf-var
        - name: SHARELATEX_SESSION_SECRET
          value: "something_really_stupid_random"
        - name: SHARELATEX_BEHIND_PROXY
          value: "true"
        - name: SHARELATEX_SECURE_COOKIE
          value: "true"
        {{- range .Values.sharelatex.environment }}
        - name: {{ .name }}
          value: {{ .value | quote  }}
        {{- end }} 
        image: {{ .Values.sharelatex.image.name }}:{{ .Values.sharelatex.image.tag }}
        imagePullPolicy: {{ .Values.sharelatex.image.pullPolicy }}
        name: sharelatex
        ports:
        - containerPort: 80
        resources: {}
        {{ if .Values.sharelatex.volumes.name }}
        volumeMounts:
        - mountPath: /var/lib/sharelatex
          name: sharelatex-data-volume
        {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      {{ if .Values.sharelatex.volumes.name }}
      volumes:
      - name: sharelatex-data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.sharelatex.volumes.name }}
      {{ end }}
status: {}
